### ISSUE TITLE
Incorrect name of executable

### ISSUE THREAD

**Issue by etherealxx** [imrofayel/fylepad#12]
The project is named `fylepad` while the installer is named `fyelpad_0.1.0_x64-setup.exe` (F-Y-E-L instead of F-Y-L-E)
not only that, the app name and window name is named as such
![image](https://github.com/user-attachments/assets/c3b41e37-76aa-4bd6-870c-234c9dcbec5a)

Maybe keep this in mind for next release. Nice app✨

**Comment by imrofayel** [comment]
![image](https://github.com/user-attachments/assets/6b2d808d-c1c0-499f-becf-a896684ce53c)

Thankyou @etherealxx for noticing this, I will fix it right now! I'm already happy that somebody is using it! 

Have a great day! ✨

**Comment by imrofayel** [comment]
@etherealxx you can **reinstall** the app now, its fixed.

[Release](https://github.com/imrofayel/fylepad/releases/tag/Windows)

**Comment by imrofayel** [comment]
@etherealxx you can **reinstall** the app now, its fixed.

[Release](https://github.com/imrofayel/fylepad/releases/tag/Windows)
