### ISSUE TITLE
Neat works on mac with signup to tiptap

### ISSUE THREAD

**Issue by jswhisperer** [imrofayel/fylepad#14]
would be cool I think to integrate
something like https://github.com/tauri-apps/tauri-action/blob/dev/.github/workflows/ci.yml
or https://github.com/tauri-apps/create-tauri-app to bundle for mac and linux more easy?

**Comment by imrofayel** [comment]
@jswhisperer I'm working on its next version slowly, once I finished I'll release `mac` and `linux` apps as well and your mentioned thing too. Or if you can do this for us? it would be really a great help. I don't have a mac machine so I can't confirm if it works there.

Thank you!

**Comment by jswhisperer** [comment]
No problem happy to do  it

**Comment by jswhisperer** [comment]
supporting PR https://github.com/imrofayel/fylepad/pull/16 for history

**Comment by jswhisperer** [comment]
New PR https://github.com/imrofayel/fylepad/pull/17

**Comment by jswhisperer** [comment]
I think double check the npm secret
<img width="656" alt="Screenshot 2024-12-02 at 1 58 19 AM" src="https://github.com/user-attachments/assets/8faaaad8-8de9-4e71-a621-95eb092e4542">

**Comment by imrofayel** [comment]
@jswhisperer I've copied from here and set as `NPM_TOKEN`
<img width="715" alt="image" src="https://github.com/user-attachments/assets/71b4f1fe-e62e-458c-9190-5a25af9cc4cf">

<img width="850" alt="image" src="https://github.com/user-attachments/assets/518ce4ee-75ff-421b-9e2e-b9da94b3cb35">

How to trigger a latest release? currently `test` release is empty.

**Comment by jswhisperer** [comment]
So manually you can always click "Actions" "Release" run
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/624f5917-b1d2-44f8-bb02-58cbfa401712">

**Comment by jswhisperer** [comment]
I will have to look tomorrow something is not working on yours but it's the same setup as mine. The build is failing. Apologies https://github.com/imrofayel/fylepad/actions/runs/12111068854/job/33808813463

**Comment by imrofayel** [comment]
Sure, I'm waiting @jswhisperer  🕊️

**Comment by jswhisperer** [comment]
Should be good to go, every push to master or main branch, no need to tag, it will pull from Cargo.toml. tested the mac builds, just double check windows. cheers.

**Comment by jswhisperer** [comment]
Feel free to edit the tags, 0.3.1 was just to bump it

**Comment by imrofayel** [comment]
@jswhisperer Thank you! 🎉

**Comment by jswhisperer** [comment]
Yes I have some ideas actually, maybe add Discussions board feature to repo?

I think we can add copy image from desktop and past to editor, and copy from editor and paste markdown or html etc out, maybe with tauri we use multi window, have one window for preview one for markdown lots of ideas :P

**Comment by imrofayel** [comment]
I've added `Discussions`. I would love to make fylepad advance than before. I'll try to handle the app section and you may try to do tauri related stuff. Let me know all of your ideas about it. 🕊️

**Comment by imrofayel** [comment]
I've made a [Ozan](https://github.com/imrofayel/Ozan/) btw. It's featured rich Obsidian inspired markdown based knowledge base. Your ideas already implemented in this app, not exactly tho. But its made with Flutter.

**Comment by jswhisperer** [comment]
I'll check it out and build it, flutter is cool

**Comment by imrofayel** [comment]
@jswhisperer Sure, you can refactor the code a little bit. It's kinda messy cause it was my first ever project as a student. If you really interested in it, I can add you as a collaborator.

Thank you btw, you are a great help. Since you joined, we went from 30 ⭐ to 40 on each projects. Having a senior developer in my newbie projects is such a blessing. Have a great day 🕊️

**Comment by jswhisperer** [comment]
No worries mate, just a bit busy now have some work after a long stretch without
