### ISSUE TITLE
Notarizing macOS software before distribution

### ISSUE THREAD

**Issue by imrofayel** [imrofayel/fylepad#26]
On `discord`, someone posted this issue.

<img width="323" alt="image" src="https://github.com/user-attachments/assets/49f0b7d2-ef51-491d-941a-d9d543a0747d" />

**Comment by jswhisperer** [comment]
I'll double check the build they can install the intel version on any mac in the meantime

**Comment by jswhisperer** [comment]
https://github.com/imrofayel/fylepad/pull/27
